
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmngcnmwifrcuztflrhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtbmdjbm13aWZyY3V6dGZscmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDA4ODUsImV4cCI6MjA3MTYxNjg4NX0.U7ToGuLaNfRtuPzALE5-xMYk3Z2cocYL8ph0Uh5PRO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
