// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfbnlwecxfomfgvpqdna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmYm5sd2VjeGZvbWZndnBxZG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTU5MTcsImV4cCI6MjA2NTUzMTkxN30.wDS_ExCpoxiGyFqgnj8fNZCYKCVGJaQz1nruJO45aHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);